### ISSUE TITLE
Make as framework?

### ISSUE THREAD

**Issue by vasilenkoigor** [SD10/Nora#16]
Hey guys! 
It's interesting project, but without supporting installation via Cocoapods or Carthage. 
How about let's do this?

**Comment by SD10** [comment]
@vasilenkoigor thank you for your interest in this project 👍

There's currently no easy way to turn this project into an actual Framework.
Firebase is a static library which prevents us from using it as a dependency for this project.

I've spent some time researching some hacks around this but it has been eating up a lot of my time and is beyond my current capabilities.
