### ISSUE TITLE
What is the pro and cons Nora vs pyrobase?

### ISSUE THREAD

**Issue by steve21124** [SD10/Nora#29]
first, thanks for writing the library and second

What is the pro and cons Nora vs pyrobase? trying to understand which one is better fit for one scenario and not the others. 

https://github.com/mownier/pyrobase

**Comment by SD10** [comment]
Hey @steve21124,
I'm not familiar with pyrobase at all so I couldn't tell you the pros and cons of the two. Nora is meant to be a [Moya like abstraction](https://github.com/Moya/Moya) for Firebase. I created this since Moya can't support Firebase due to it being so tightly coupled to Alamofire.

**Comment by steve21124** [comment]
Thanks @SD10, I am trying to check if Nora can fits the needs. There is currently no example of demo example having table view. So I am not sure from quick glance how useful it is. another framework, that i am checking is https://github.com/1amageek/Salada.
